name: Rcam
options:
  bundleIdPrefix: com.rosberry
targets:
  Rcam:
    type: framework
    platform: iOS
    sources: [Sources/Rcam]
    info:
      path: Rcam.xcodeproj/Rcam.plist
  RcamTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Tests/RcamTests]
    info:
      path: Rcam.xcodeproj/RcamTests.plist
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
  Example:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Sources/Example]
    info:
      path: Rcam.xcodeproj/Example.plist
    dependencies:
      - target: Rcam
    postCompileScripts:
      - script: swiftlint
        name: Swiftlint
